pip install flask
pip install flask-login
pip install flask-openid
pip install flask-mail
pip install sqlalchemy
pip install flask-sqlalchemy
pip install sqlalchemy-migrate
pip install flask-whooshalchemy
pip install flask-wtf
pip install pytz
pip install flask-babel
pip install flup
pip install beautifulsoup4
pip install lxml
pip install flask-restful
pip install requests
